application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      hello-app:
        license: Apache-2.0
        actions:
          greet:
            function: actions/greet/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
